//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;realm&quot;: &quot;Medivh&quot;, &quot;name&quot;: &quot;Uther&quot;, &quot;level&quot;: 85, &quot;lastModified&quot;: 1307596000000, &quot;thumbnail&quot;: &quot;medivh/1/1-avatar.jpg&quot;,
        ///&quot;race&quot;: 1, &quot;achievementPoints&quot;: 9745, &quot;gender&quot;: 0, &quot;class&quot;: 2}.
        /// </summary>
        internal static string char1 {
            get {
                return ResourceManager.GetString("char1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;classes&quot;:[
        ///    {
        ///      &quot;id&quot;:3,
        ///      &quot;mask&quot;:4,
        ///      &quot;powerType&quot;:&quot;focus&quot;,
        ///      &quot;name&quot;:&quot;Hunter&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:1,
        ///      &quot;mask&quot;:1,
        ///      &quot;powerType&quot;:&quot;rage&quot;,
        ///      &quot;name&quot;:&quot;Warrior&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:5,
        ///      &quot;mask&quot;:16,
        ///      &quot;powerType&quot;:&quot;mana&quot;,
        ///      &quot;name&quot;:&quot;Priest&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:9,
        ///      &quot;mask&quot;:256,
        ///      &quot;powerType&quot;:&quot;mana&quot;,
        ///      &quot;name&quot;:&quot;Warlock&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:7,
        ///      &quot;mask&quot;:64,
        ///      &quot;powerType&quot;:&quot;mana&quot;,
        ///      &quot;name&quot;:&quot;Shaman&quot;
        ///    },
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;rewards&quot;:[
        ///    {
        ///      &quot;minGuildLevel&quot;:0,
        ///      &quot;minGuildRepLevel&quot;:6,
        ///      &quot;races&quot;:[6,5,2,8,9,10],
        ///      &quot;achievement&quot;:{
        ///        &quot;id&quot;:5035,
        ///        &quot;title&quot;:&quot;Master Crafter&quot;,
        ///        &quot;points&quot;:10,
        ///        &quot;description&quot;:&quot;Craft 500 Epic items with an item level of at least 359.&quot;,
        ///        &quot;reward&quot;:&quot;Reward: Cloak of Coordination&quot;,
        ///        &quot;rewardItem&quot;:{
        ///          &quot;id&quot;:65360,
        ///          &quot;name&quot;:&quot;Cloak of Coordination&quot;,
        ///          &quot;icon&quot;:&quot;inv_guild_cloak_alliance_c&quot;,
        ///          &quot;quality&quot;:4,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string guildrewards {
            get {
                return ResourceManager.GetString("guildrewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;perks&quot;:[
        ///    {
        ///      &quot;guildLevel&quot;:2,
        ///      &quot;spell&quot;:{
        ///        &quot;id&quot;:78631,
        ///        &quot;name&quot;:&quot;Fast Track&quot;,
        ///        &quot;subtext&quot;:&quot;Rank 1&quot;,
        ///        &quot;icon&quot;:&quot;achievement_guildperk_fasttrack&quot;,
        ///        &quot;description&quot;:&quot;Experience gained from killing monsters and completing quests increased by 5%.&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;guildLevel&quot;:3,
        ///      &quot;spell&quot;:{
        ///        &quot;id&quot;:78633,
        ///        &quot;name&quot;:&quot;Mount Up&quot;,
        ///        &quot;icon&quot;:&quot;achievement_guildperk_mountup&quot;,
        ///        &quot;description&quot;:&quot;Increases speed while mounted [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string perks {
            get {
                return ResourceManager.GetString("perks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;races&quot;:[
        ///    {
        ///      &quot;id&quot;:3,
        ///      &quot;mask&quot;:4,
        ///      &quot;side&quot;:&quot;alliance&quot;,
        ///      &quot;name&quot;:&quot;Dwarf&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:6,
        ///      &quot;mask&quot;:32,
        ///      &quot;side&quot;:&quot;horde&quot;,
        ///      &quot;name&quot;:&quot;Tauren&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:5,
        ///      &quot;mask&quot;:16,
        ///      &quot;side&quot;:&quot;horde&quot;,
        ///      &quot;name&quot;:&quot;Undead&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:2,
        ///      &quot;mask&quot;:2,
        ///      &quot;side&quot;:&quot;horde&quot;,
        ///      &quot;name&quot;:&quot;Orc&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:7,
        ///      &quot;mask&quot;:64,
        ///      &quot;side&quot;:&quot;alliance&quot;,
        ///      &quot;name&quot;:&quot;Gnome&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;:8,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string race1 {
            get {
                return ResourceManager.GetString("race1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;realms&quot;:[
        ///    {
        ///      &quot;type&quot;:&quot;pvp&quot;,
        ///      &quot;queue&quot;:false,
        ///      &quot;status&quot;:true,
        ///      &quot;population&quot;:&quot;low&quot;,
        ///      &quot;name&quot;:&quot;Aegwynn&quot;,
        ///      &quot;slug&quot;:&quot;aegwynn&quot;
        ///    },
        ///    {
        ///      &quot;type&quot;:&quot;pve&quot;,
        ///      &quot;queue&quot;:false,
        ///      &quot;status&quot;:true,
        ///      &quot;population&quot;:&quot;high&quot;,
        ///      &quot;name&quot;:&quot;Aerie Peak&quot;,
        ///      &quot;slug&quot;:&quot;aerie-peak&quot;
        ///    }
        ///]
        ///}.
        /// </summary>
        internal static string realm1 {
            get {
                return ResourceManager.GetString("realm1", resourceCulture);
            }
        }
    }
}
